"""
Physics-Informed Basic LNN with Reactive Power for NILM — WHITED.

Extends the standard PINN-BasicLNN with three additional physics constraints:

  1. Active-power conservation (P)   — ReLU(sum P_hat_i - P_agg - eps_P)
     Already in test_pinn_basic_lnn_whited_specific_splits.py.

  2. Reactive-power conservation (Q) — |sum Q_hat_i - Q_agg|
     WHITED provides raw V+I waveforms, so Q is computed at the 50 Hz
     fundamental (Austrian grid) via DFT.  Q > 0 for inductive loads
     (fridge, washing machine), Q ~= 0 for resistive loads (kettle).
     Using both P and Q as input features helps discriminate appliance types
     that look similar in active power alone.

  3. Non-negativity on predicted P   — ReLU(-P_hat_raw)

  4. Per-appliance P upper-bound     — ReLU(P_hat_scaled - 1.0)
     MinMaxScaler maps the training maximum to 1.0; predictions exceeding
     this are physically impossible given the observed data.

Input:  (batch, WIN, 2)  — [P_agg_scaled, Q_agg_scaled] per timestep
Model:  BasicLiquidTimeLayer (fixed tau) -> LayerNorm
        -> per-appliance P heads + per-appliance Q heads
Output: P_hat (batch, n_app), Q_hat (batch, n_app)

Loss stages:
  Stage 1 (epochs 1-WARMUP_EPOCHS): MSE_P + MSE_Q only
  Stage 2 (remaining):              MSE_P + MSE_Q
                                    + lambda_P * L_phys_P
                                    + lambda_Q * L_phys_Q
                                    + lambda_nonneg * L_nonneg
                                    + lambda_bounds * L_bounds
                                    + weighted BCE (P only)

Requires pkl files generated by the updated make_whited_pkl.py
which adds columns: main_q, fridge_q, microwave_q, washing machine_q, kettle_q.
"""

import sys
import os
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
import json
from datetime import datetime
from tqdm import tqdm
import pickle
from sklearn.preprocessing import MinMaxScaler

sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'Source Code'))
from utils import calculate_nilm_metrics, save_model


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

EPOCHS        = 80
PATIENCE      = 20
LR            = 1e-3
BATCH         = 32
WIN           = 100
STRIDE        = 5

WARMUP_EPOCHS = 20

# Physics loss weights
LAMBDA_PHYS_P  = 0.01   # active-power conservation
LAMBDA_PHYS_Q  = 0.01   # reactive-power conservation
LAMBDA_NONNEG  = 0.005  # non-negativity on P
LAMBDA_BOUNDS  = 0.005  # P upper-bound (scaled > 1.0)

EPSILON_P = 50.0   # tolerance on P sum violation (Watts)
EPSILON_Q = 30.0   # tolerance on Q sum violation (VAR)

APPLIANCES = ['fridge', 'microwave', 'washing machine', 'kettle']

THRESHOLDS = {
    'fridge':           50.0,
    'microwave':        50.0,
    'washing machine':   5.0,
    'kettle':           50.0,
}

BCE_LAMBDA = {'fridge': 0.3, 'microwave': 0.3, 'washing machine': 0.3, 'kettle': 0.3}
BCE_ALPHA  = {'fridge': 1.5, 'microwave': 1.5, 'washing machine': 4.0, 'kettle': 1.5}


# ---------------------------------------------------------------------------
# Multi-physics loss
# ---------------------------------------------------------------------------

class MultiPhysicsLoss(nn.Module):
    """
    Differentiable physics constraints using inverse MinMaxScaler transforms.

    Registered buffers store the scaler parameters so the loss module can
    move to GPU with .to(device).
    """

    def __init__(self, p_scaler, q_scaler, yp_scalers, yq_scalers,
                 appliances, epsilon_p=EPSILON_P, epsilon_q=EPSILON_Q):
        super().__init__()
        self.epsilon_p = epsilon_p
        self.epsilon_q = epsilon_q

        # Mains P inverse-scale params
        self.register_buffer('p_min',   torch.tensor(float(p_scaler.data_min_[0])))
        self.register_buffer('p_range', torch.tensor(float(p_scaler.data_range_[0])))

        # Mains Q inverse-scale params
        self.register_buffer('q_min',   torch.tensor(float(q_scaler.data_min_[0])))
        self.register_buffer('q_range', torch.tensor(float(q_scaler.data_range_[0])))

        # Per-appliance P inverse-scale params
        yp_mins   = [float(yp_scalers[i].data_min_[0])   for i in range(len(appliances))]
        yp_ranges = [float(yp_scalers[i].data_range_[0]) for i in range(len(appliances))]
        self.register_buffer('yp_mins',   torch.tensor(yp_mins,   dtype=torch.float32))
        self.register_buffer('yp_ranges', torch.tensor(yp_ranges, dtype=torch.float32))

        # Per-appliance Q inverse-scale params
        yq_mins   = [float(yq_scalers[i].data_min_[0])   for i in range(len(appliances))]
        yq_ranges = [float(yq_scalers[i].data_range_[0]) for i in range(len(appliances))]
        self.register_buffer('yq_mins',   torch.tensor(yq_mins,   dtype=torch.float32))
        self.register_buffer('yq_ranges', torch.tensor(yq_ranges, dtype=torch.float32))

    def forward(self, p_agg_sc, q_agg_sc, p_pred_sc, q_pred_sc):
        """
        Args:
            p_agg_sc:  (batch,)       scaled P_agg at window midpoint
            q_agg_sc:  (batch,)       scaled Q_agg at window midpoint
            p_pred_sc: (batch, n_app) scaled per-appliance P predictions
            q_pred_sc: (batch, n_app) scaled per-appliance Q predictions
        Returns:
            l_phys_p, l_phys_q, l_nonneg, l_bounds  — all scalar tensors
        """
        # Inverse-scale to raw Watts / VAR
        p_agg_raw  = p_agg_sc * self.p_range + self.p_min     # (batch,)
        q_agg_raw  = q_agg_sc * self.q_range + self.q_min     # (batch,)
        p_pred_raw = p_pred_sc * self.yp_ranges + self.yp_mins  # (batch, n_app)
        q_pred_raw = q_pred_sc * self.yq_ranges + self.yq_mins  # (batch, n_app)

        # 1. Active-power conservation (one-sided: background loads absorb slack)
        l_phys_p = F.relu(p_pred_raw.sum(dim=1) - p_agg_raw - self.epsilon_p).mean()

        # 2. Reactive-power conservation (symmetric: Q can go either sign)
        l_phys_q = (q_pred_raw.sum(dim=1) - q_agg_raw).abs().clamp(min=self.epsilon_q).mean()

        # 3. Non-negativity on predicted P (power consumption >= 0)
        l_nonneg = F.relu(-p_pred_raw).mean()

        # 4. Per-appliance P upper-bound (predictions > scaled maximum = 1.0)
        l_bounds = F.relu(p_pred_sc - 1.0).mean()

        return l_phys_p, l_phys_q, l_nonneg, l_bounds


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------

class ReactivePowerBasicLNNModel(nn.Module):
    """
    BasicLiquidTimeLayer (fixed tau) on 2-channel input [P_agg, Q_agg].

    Per-appliance heads produce both P and Q predictions so the reactive-power
    conservation constraint is differentiable end-to-end.

    Cell update:
        tau   = softplus(tau_param)
        f_t   = tanh(LayerNorm(W_in * x_t + W_rec * h))
        dh    = (-h / tau + f_t) * dt
        h_new = clamp(h + dh, -10, 10)
    """

    def __init__(self, input_size=2, hidden_size=64, n_appliances=4, dt=0.1):
        super().__init__()
        self.hidden_size  = hidden_size
        self.n_appliances = n_appliances
        self.dt           = dt

        self.input_proj  = nn.Linear(input_size, hidden_size)
        self.tau         = nn.Parameter(torch.ones(hidden_size))
        self.rec_weights = nn.Parameter(torch.empty(hidden_size, hidden_size))
        nn.init.xavier_uniform_(self.rec_weights)

        self.intra_norm = nn.LayerNorm(hidden_size)
        self.norm       = nn.LayerNorm(hidden_size)

        self.p_heads = nn.ModuleList([nn.Linear(hidden_size, 1) for _ in range(n_appliances)])
        self.q_heads = nn.ModuleList([nn.Linear(hidden_size, 1) for _ in range(n_appliances)])

    def forward(self, x):
        """
        Args:
            x: (batch, seq_len, 2)  — [P_agg_scaled, Q_agg_scaled]
        Returns:
            p_out: (batch, n_appliances)
            q_out: (batch, n_appliances)
        """
        batch_size, seq_len, _ = x.size()
        h   = torch.zeros(batch_size, self.hidden_size, device=x.device)
        tau = F.softplus(self.tau).unsqueeze(0)

        for t in range(seq_len):
            x_t   = x[:, t, :]
            f_t   = torch.tanh(self.intra_norm(self.input_proj(x_t) + torch.matmul(h, self.rec_weights)))
            dh    = (-h / tau + f_t) * self.dt
            h     = (h + dh).clamp(-10.0, 10.0)

        h = self.norm(h)
        p_out = torch.cat([head(h) for head in self.p_heads], dim=1)
        q_out = torch.cat([head(h) for head in self.q_heads], dim=1)
        return p_out, q_out


# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------

class WHITEDDataset(torch.utils.data.Dataset):
    def __init__(self, X, Y_P, Y_Q):
        self.X   = torch.FloatTensor(X)
        self.Y_P = torch.FloatTensor(Y_P)
        self.Y_Q = torch.FloatTensor(Y_Q)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.Y_P[idx], self.Y_Q[idx]


# ---------------------------------------------------------------------------
# Data helpers
# ---------------------------------------------------------------------------

def load_data():
    print("Loading WHITED data (with reactive power columns) ...")
    splits = {}
    for name in ('train', 'val', 'test'):
        with open(f'data/WHITED_enriched/{name}.pkl', 'rb') as f:
            splits[name] = pickle.load(f)[0]
    for name, df in splits.items():
        print(f"  {name:5s}: {df.shape}  cols={list(df.columns)}")
    return splits


def create_sequences(data, window_size=WIN):
    """
    Returns:
        X:   (N, WIN, 2)  — [P_agg, Q_agg] per timestep
        Y_P: (N, n_app)   — active power at window midpoint
        Y_Q: (N, n_app)   — reactive power at window midpoint
    """
    mains_p = data['main'].values
    mains_q = data['main_q'].values
    app_p   = {app: data[app].values          for app in APPLIANCES}
    app_q   = {app: data[f'{app}_q'].values   for app in APPLIANCES}
    X, Y_P, Y_Q = [], [], []
    for i in range(0, len(mains_p) - window_size, STRIDE):
        X.append(np.stack([mains_p[i:i+window_size],
                           mains_q[i:i+window_size]], axis=1))   # (WIN, 2)
        mid = i + window_size // 2
        Y_P.append([app_p[app][mid] for app in APPLIANCES])
        Y_Q.append([app_q[app][mid] for app in APPLIANCES])
    return (np.array(X,   dtype=np.float32),
            np.array(Y_P, dtype=np.float32),
            np.array(Y_Q, dtype=np.float32))


# ---------------------------------------------------------------------------
# Per-appliance metrics
# ---------------------------------------------------------------------------

def compute_metrics(y_true_p, y_pred_p, yp_scalers):
    metrics = {}
    for i, app in enumerate(APPLIANCES):
        raw_true = yp_scalers[i].inverse_transform(y_true_p[:, i:i+1]).flatten()
        raw_pred = yp_scalers[i].inverse_transform(y_pred_p[:, i:i+1]).flatten()
        metrics[app] = calculate_nilm_metrics(raw_true, raw_pred, threshold=THRESHOLDS[app])
    return metrics


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------

def train_model(data_dict, save_dir, hidden_size=64, dt=0.1):
    os.makedirs(save_dir, exist_ok=True)
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Device: {device}  hidden={hidden_size}  dt={dt}")
    print(f"Physics weights: lambda_P={LAMBDA_PHYS_P}  lambda_Q={LAMBDA_PHYS_Q}  "
          f"lambda_nonneg={LAMBDA_NONNEG}  lambda_bounds={LAMBDA_BOUNDS}")
    print(f"Tolerances: eps_P={EPSILON_P} W  eps_Q={EPSILON_Q} VAR")

    # ── Sequences ──────────────────────────────────────────────────────────
    X_tr, YP_tr, YQ_tr = create_sequences(data_dict['train'], WIN)
    X_va, YP_va, YQ_va = create_sequences(data_dict['val'],   WIN)
    X_te, YP_te, YQ_te = create_sequences(data_dict['test'],  WIN)

    # ── Scaling ────────────────────────────────────────────────────────────
    # Separate scalers for P_agg and Q_agg channels
    p_scaler = MinMaxScaler()
    q_scaler = MinMaxScaler()

    X_tr_p = p_scaler.fit_transform(X_tr[:, :, 0].reshape(-1, 1)).reshape(X_tr.shape[0], WIN)
    X_tr_q = q_scaler.fit_transform(X_tr[:, :, 1].reshape(-1, 1)).reshape(X_tr.shape[0], WIN)
    X_va_p = p_scaler.transform(X_va[:, :, 0].reshape(-1, 1)).reshape(X_va.shape[0], WIN)
    X_va_q = q_scaler.transform(X_va[:, :, 1].reshape(-1, 1)).reshape(X_va.shape[0], WIN)
    X_te_p = p_scaler.transform(X_te[:, :, 0].reshape(-1, 1)).reshape(X_te.shape[0], WIN)
    X_te_q = q_scaler.transform(X_te[:, :, 1].reshape(-1, 1)).reshape(X_te.shape[0], WIN)

    X_tr = np.stack([X_tr_p, X_tr_q], axis=2)  # (N, WIN, 2)
    X_va = np.stack([X_va_p, X_va_q], axis=2)
    X_te = np.stack([X_te_p, X_te_q], axis=2)

    # Per-appliance P and Q scalers
    yp_scalers, yq_scalers = [], []
    for i in range(len(APPLIANCES)):
        yps = MinMaxScaler(); yqs = MinMaxScaler()
        YP_tr[:, i:i+1] = yps.fit_transform(YP_tr[:, i:i+1])
        YP_va[:, i:i+1] = yps.transform(YP_va[:, i:i+1])
        YP_te[:, i:i+1] = yps.transform(YP_te[:, i:i+1])
        YQ_tr[:, i:i+1] = yqs.fit_transform(YQ_tr[:, i:i+1])
        YQ_va[:, i:i+1] = yqs.transform(YQ_va[:, i:i+1])
        YQ_te[:, i:i+1] = yqs.transform(YQ_te[:, i:i+1])
        yp_scalers.append(yps)
        yq_scalers.append(yqs)

    thresholds_scaled = [
        (THRESHOLDS[app] - float(yp_scalers[i].data_min_[0]))
        / float(yp_scalers[i].data_range_[0])
        for i, app in enumerate(APPLIANCES)
    ]

    print(f"Train: {X_tr.shape}  YP:{YP_tr.shape}  YQ:{YQ_tr.shape}")
    print(f"Val:   {X_va.shape}  YP:{YP_va.shape}  YQ:{YQ_va.shape}")
    print(f"Test:  {X_te.shape}  YP:{YP_te.shape}  YQ:{YQ_te.shape}")

    tr_loader = torch.utils.data.DataLoader(
        WHITEDDataset(X_tr, YP_tr, YQ_tr), batch_size=BATCH, shuffle=True,  drop_last=False)
    va_loader = torch.utils.data.DataLoader(
        WHITEDDataset(X_va, YP_va, YQ_va), batch_size=BATCH, shuffle=False, drop_last=False)
    te_loader = torch.utils.data.DataLoader(
        WHITEDDataset(X_te, YP_te, YQ_te), batch_size=BATCH, shuffle=False, drop_last=False)

    # ── Model + losses ─────────────────────────────────────────────────────
    model = ReactivePowerBasicLNNModel(
        input_size=2, hidden_size=hidden_size,
        n_appliances=len(APPLIANCES), dt=dt,
    ).to(device)

    mse_loss    = nn.MSELoss()
    phys_loss   = MultiPhysicsLoss(
        p_scaler, q_scaler, yp_scalers, yq_scalers,
        APPLIANCES, epsilon_p=EPSILON_P, epsilon_q=EPSILON_Q,
    ).to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr=LR)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode='min', factor=0.5, patience=8, min_lr=1e-5)

    history = {
        'train_loss': [], 'val_loss': [],
        'train_mse_p': [], 'train_mse_q': [],
        'val_mse_p':   [], 'val_mse_q':   [],
        'val_metrics': [],
    }
    best_val_loss = float('inf')
    best_state    = None
    counter       = 0

    n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"Parameters: {n_params:,}")
    print("Starting PINN-ReactivePower-BasicLNN training ...")

    for epoch in range(EPOCHS):
        # ── Train ──────────────────────────────────────────────────────────
        model.train()
        ep_total = ep_mse_p = ep_mse_q = 0.0
        pbar = tqdm(tr_loader, desc=f"Epoch {epoch+1}/{EPOCHS}", leave=False)

        for xb, yb_p, yb_q in pbar:
            xb, yb_p, yb_q = xb.to(device), yb_p.to(device), yb_q.to(device)
            optimizer.zero_grad()

            p_pred, q_pred = model(xb)

            l_mse_p = mse_loss(p_pred, yb_p)
            l_mse_q = mse_loss(q_pred, yb_q)

            p_mid = xb[:, WIN // 2, 0]   # scaled P_agg at midpoint
            q_mid = xb[:, WIN // 2, 1]   # scaled Q_agg at midpoint

            if epoch < WARMUP_EPOCHS:
                loss = l_mse_p + l_mse_q
            else:
                l_pp, l_pq, l_nn, l_bd = phys_loss(p_mid, q_mid, p_pred, q_pred)

                bce = torch.tensor(0.0, device=device)
                for i, app in enumerate(APPLIANCES):
                    if BCE_LAMBDA[app] > 0:
                        pi    = p_pred[:, i].clamp(1e-7, 1 - 1e-7)
                        y_bin = (yb_p[:, i] > thresholds_scaled[i]).float()
                        w     = torch.where(y_bin == 1,
                                            torch.full_like(y_bin, BCE_ALPHA[app]),
                                            torch.ones_like(y_bin))
                        bce = bce + BCE_LAMBDA[app] * F.binary_cross_entropy(pi, y_bin, weight=w)

                loss = (l_mse_p + l_mse_q
                        + LAMBDA_PHYS_P  * l_pp
                        + LAMBDA_PHYS_Q  * l_pq
                        + LAMBDA_NONNEG  * l_nn
                        + LAMBDA_BOUNDS  * l_bd
                        + bce)

            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()

            ep_total += loss.item()
            ep_mse_p += l_mse_p.item()
            ep_mse_q += l_mse_q.item()
            pbar.set_postfix({'mse_p': f'{l_mse_p.item():.5f}',
                              'mse_q': f'{l_mse_q.item():.5f}'})

        n_tr = len(tr_loader)
        history['train_loss'].append(ep_total / n_tr)
        history['train_mse_p'].append(ep_mse_p / n_tr)
        history['train_mse_q'].append(ep_mse_q / n_tr)

        # ── Validate ───────────────────────────────────────────────────────
        model.eval()
        vl_total = vl_mse_p = vl_mse_q = 0.0
        val_pp, val_pt = [], []

        with torch.no_grad():
            for xb, yb_p, yb_q in va_loader:
                xb, yb_p, yb_q = xb.to(device), yb_p.to(device), yb_q.to(device)
                p_pred, q_pred  = model(xb)
                l_mse_p = mse_loss(p_pred, yb_p)
                l_mse_q = mse_loss(q_pred, yb_q)
                vl_mse_p += l_mse_p.item()
                vl_mse_q += l_mse_q.item()
                vl_total += (l_mse_p + l_mse_q).item()
                val_pp.append(p_pred.cpu().numpy())
                val_pt.append(yb_p.cpu().numpy())

        n_va = len(va_loader)
        avg_va_total = vl_total / n_va
        history['val_loss'].append(avg_va_total)
        history['val_mse_p'].append(vl_mse_p / n_va)
        history['val_mse_q'].append(vl_mse_q / n_va)

        scheduler.step(vl_mse_p / n_va)

        yp_pred_all = np.concatenate(val_pp)
        yp_true_all = np.concatenate(val_pt)
        per_app     = compute_metrics(yp_true_all, yp_pred_all, yp_scalers)
        history['val_metrics'].append(per_app)

        avg_f1  = np.mean([per_app[a]['f1']  for a in APPLIANCES])
        avg_mae = np.mean([per_app[a]['mae'] for a in APPLIANCES])

        print(f"  Epoch {epoch+1:3d}/{EPOCHS}  "
              f"train={ep_total/n_tr:.5f}  val={avg_va_total:.5f}  "
              f"avgF1={avg_f1:.4f}  avgMAE={avg_mae:.2f}  "
              f"lr={optimizer.param_groups[0]['lr']:.2e}")
        for app in APPLIANCES:
            m = per_app[app]
            print(f"    {app:<16}  F1={m['f1']:.4f}  "
                  f"P={m['precision']:.4f}  R={m['recall']:.4f}  "
                  f"MAE={m['mae']:.2f}  SAE={m['sae']:.4f}")

        if avg_va_total < best_val_loss:
            best_val_loss = avg_va_total
            best_state    = {k: v.clone() for k, v in model.state_dict().items()}
            counter       = 0
        else:
            counter += 1
            if counter >= PATIENCE:
                print(f"  Early stopping at epoch {epoch+1}")
                break

    print("Training completed!")

    # ── Test ───────────────────────────────────────────────────────────────
    if best_state is not None:
        model.load_state_dict(best_state)
    model.eval()

    te_pp, te_pt = [], []
    with torch.no_grad():
        for xb, yb_p, _ in te_loader:
            p_pred, _ = model(xb.to(device))
            te_pp.append(p_pred.cpu().numpy())
            te_pt.append(yb_p.numpy())

    test_metrics = compute_metrics(np.concatenate(te_pt),
                                   np.concatenate(te_pp), yp_scalers)

    print(f"\n{'Appliance':<17} {'F1':>8} {'Precision':>10} {'Recall':>8} "
          f"{'MAE':>8} {'SAE':>8}")
    print("-" * 65)
    for app in APPLIANCES:
        m = test_metrics[app]
        print(f"{app:<17} {m['f1']:>8.4f} {m['precision']:>10.4f} "
              f"{m['recall']:>8.4f} {m['mae']:>8.2f} {m['sae']:>8.4f}")

    _plot(history, test_metrics, save_dir)

    config = {
        'dataset': 'WHITED',
        'model': 'ReactivePowerBasicLNNModel',
        'description': (
            'BasicLNN (fixed tau) on [P_agg, Q_agg] input + P/Q conservation '
            '+ non-negativity + bounds constraints'
        ),
        'physics': {
            'lambda_phys_p': LAMBDA_PHYS_P, 'epsilon_p_W': EPSILON_P,
            'lambda_phys_q': LAMBDA_PHYS_Q, 'epsilon_q_VAR': EPSILON_Q,
            'lambda_nonneg': LAMBDA_NONNEG,  'lambda_bounds': LAMBDA_BOUNDS,
        },
        'window_size': WIN,
        'model_params': {'input_size': 2, 'hidden_size': hidden_size,
                         'n_appliances': len(APPLIANCES), 'dt': dt},
        'train_params': {'lr': LR, 'epochs': EPOCHS, 'patience': PATIENCE,
                         'warmup_epochs': WARMUP_EPOCHS},
        'test_metrics': {app: {k: float(v) for k, v in m.items()}
                         for app, m in test_metrics.items()},
    }
    with open(os.path.join(save_dir, 'pinn_reactive_power_lnn_whited_results.json'),
              'w', encoding='utf-8') as f:
        json.dump(config, f, indent=4)

    return test_metrics, history


# ---------------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------------

def _plot(history, test_metrics, save_dir):
    epochs_x = range(1, len(history['train_loss']) + 1)

    plt.figure(figsize=(15, 4))

    plt.subplot(1, 3, 1)
    plt.plot(epochs_x, history['train_loss'], label='Train total', color='blue')
    plt.plot(epochs_x, history['val_loss'],   label='Val total',   color='red')
    plt.title('Total Loss'); plt.xlabel('Epoch'); plt.ylabel('Loss')
    plt.legend(); plt.grid(True, alpha=0.3)

    plt.subplot(1, 3, 2)
    plt.plot(epochs_x, history['train_mse_p'], label='Train MSE_P', color='blue')
    plt.plot(epochs_x, history['val_mse_p'],   label='Val MSE_P',   color='red')
    plt.title('Active Power MSE'); plt.xlabel('Epoch'); plt.ylabel('MSE')
    plt.legend(); plt.grid(True, alpha=0.3)

    plt.subplot(1, 3, 3)
    plt.plot(epochs_x, history['train_mse_q'], label='Train MSE_Q', color='blue')
    plt.plot(epochs_x, history['val_mse_q'],   label='Val MSE_Q',   color='red')
    plt.title('Reactive Power MSE'); plt.xlabel('Epoch'); plt.ylabel('MSE')
    plt.legend(); plt.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, 'pinn_reactive_power_lnn_whited_loss.png'),
                dpi=150, bbox_inches='tight')
    plt.close()

    fig, axes = plt.subplots(len(APPLIANCES), 2, figsize=(12, 4 * len(APPLIANCES)))
    fig.suptitle('PINN-ReactivePower-LNN WHITED -- Per-Appliance Val Metrics', fontsize=13)

    for row, app in enumerate(APPLIANCES):
        f1_series  = [m[app]['f1']  for m in history['val_metrics']]
        mae_series = [m[app]['mae'] for m in history['val_metrics']]
        ax_f1, ax_mae = axes[row]

        ax_f1.plot(epochs_x, f1_series, color='blue', linewidth=1.5)
        ax_f1.axhline(test_metrics[app]['f1'], color='green', linestyle='--', label='Test F1')
        ax_f1.set_title(f'{app} -- F1'); ax_f1.set_xlabel('Epoch'); ax_f1.set_ylabel('F1')
        ax_f1.legend(); ax_f1.grid(True, alpha=0.3)

        ax_mae.plot(epochs_x, mae_series, color='red', linewidth=1.5)
        ax_mae.axhline(test_metrics[app]['mae'], color='green', linestyle='--', label='Test MAE')
        ax_mae.set_title(f'{app} -- MAE (W)'); ax_mae.set_xlabel('Epoch'); ax_mae.set_ylabel('MAE (W)')
        ax_mae.legend(); ax_mae.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, 'pinn_reactive_power_lnn_whited_per_appliance.png'),
                dpi=150, bbox_inches='tight')
    plt.close()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    for f in ['data/WHITED_enriched/train.pkl', 'data/WHITED_enriched/val.pkl', 'data/WHITED_enriched/test.pkl']:
        if not os.path.exists(f):
            print(f"Error: {f} not found!")
            sys.exit(1)

    # Quick check that pkl files have the reactive-power columns
    import pickle as _pkl
    with open('data/WHITED_enriched/train.pkl', 'rb') as _f:
        _df = _pkl.load(_f)[0]
    if 'main_q' not in _df.columns:
        print("Error: pkl files missing reactive-power columns.")
        print("Please re-run make_whited_pkl.py first.")
        sys.exit(1)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    save_dir  = f"models/pinn_reactive_power_lnn_whited_{timestamp}"

    data_dict = load_data()

    test_metrics, history = train_model(
        data_dict,
        save_dir    = save_dir,
        hidden_size = 64,
        dt          = 0.1,
    )

    print(f"\nResults saved to {save_dir}")
